print("hello world")
print('hello world')
print("hello 'word' world")
print('hello "word" world')
# in # will not work
#print("hello "word' world")
#print('hello 'word" world')
#print("hello "word" world")
#print('hello 'word' world')
#print('I'm Nilesh)
print("I'm Nilesh")